[package]
name = "tec-8-compiler"
version = "0.1.0"
authors = ["hyiker <hyiker@bupt.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"